var IntWL = {
  en: {
    name: "English",
    head: "Languages",
    url: "https://wanderers-library.wikidot.com/",
    id: "146034",
    category: "",
  },
  cn: {
    name: "中文",
    head: "其他语言",
    url: "https://scp-wiki-cn.wikidot.com/",
    id: "530812",
    category: "wanderers:",
  },
  fr: {
    name: "Français",
    head: "Dans d’autres langues",
    url: "https://fondationscp.wikidot.com/",
    id: "464696",
    category: "wanderers:",
  },
  de: {
    name: "Deutsch",
    head: "In anderen Sprachen",
    url: "https://scp-wiki-de.wikidot.com/",
    id: "1269857",
    category: "wanderers:",
  },
  it: {
    name: "Italiano",
    head: "In altre lingue",
    url: "https://fondazionescp.wikidot.com/",
    id: "530167",
    category: "wanderers:",
  },
  jp: {
    name: "日本語",
    head: "他言語版",
    url: "https://wanderers-library-jp.wikidot.com/",
    id: "4600658",
    category: "",
  },
  ko: {
    name: "한국어",
    head: "다른 언어",
    url: "https://wanderers-library-ko.wikidot.com/",
    id: "621849",
    category: "",
  },
  pl: {
    name: "Polski",
    head: "W innych językach",
    url: "https://wanderers-library-pl.wikidot.com/",
    id: "4593099",
    category: "",
  },
  "pt-br": {
    name: "Português",
    head: "Em outros idiomas",
    url: "https://scp-pt-br.wikidot.com/",
    id: "783633",
    category: "wanderers:",
  },
  ru: {
    name: "Русский",
    head: "На других языках",
    url: "https://scpfoundation.net/",
    id: "169125",
    category: "wanderers:",
  },
  es: {
    name: "Español",
    head: "En otros idiomas",
    url: "https://lafundacionscp.wikidot.com/",
    id: "560484",
    category: "wanderers:",
  },
  th: {
    name: "ภาษาไทย",
    head: "ภาษาอื่น",
    url: "https://scp-th.wikidot.com/",
    id: "547203",
    category: "wanderers:",
  },
  ua: {
    name: "Українська",
    head: "Іншими мовами",
    url: "https://scp-ukrainian.wikidot.com/",
    id: "1398197",
    category: "wanderers:",
  },
  cs: {
    name: "Čeština",
    head: "V jiných jazycích",
    url: "https://wanderers-library-cs.wikidot.com/",
    id: "4600566",
    category: "",
  },
};
