name: preview PR
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - css/**
      - html/**
      - js/**
      - build.js
      - .github/workflows/preview.yml
concurrency: preview-${{ github.ref }}
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: dist
